const { Router } = require('express')

const router = Router();

const rolRoutes = require('./rol.routes')
const colaboradorRoutes = require('./colaborador.routes')
const tipoPlatilloRoutes = require('./tipoPlatillo.routes')
const platilloRoutes = require('./platillo.routes')
const platilloDetalleRoutes = require('./platilloDetalle.routes')
const proveedorRoutes = require('./proveedor.routes')
const tipoMedidaRoutes = require('./tipoMedida.routes')
const categoriaRoutes = require('./categoria.routes')
const productoRoutes = require('./producto.routes')
const extraRoutes = require('./extra.routes')
const tipoPedidoRoutes = require('./tipoPedido.routes')
const clienteRoutes = require('./cliente.routes')
const direccionRoutes = require('./direccion.routes')
const pedidoRoutes = require('./pedido.routes')
const promocionRoutes = require('./promocion.routes')
const uploadRoutes = require('./upload.routes')

//rutas web
router.use('/api-web/rol', rolRoutes)
router.use('/api-web/colaborador', colaboradorRoutes)
router.use('/api-web/tipoPlatillo', tipoPlatilloRoutes)
router.use('/api-web/platillo', platilloRoutes)
router.use('/api-web/platilloDetalle', platilloDetalleRoutes)
router.use('/api-web/proveedor', proveedorRoutes)
router.use('/api-web/tipoMedida', tipoMedidaRoutes)
router.use('/api-web/categoria', categoriaRoutes)
router.use('/api-web/producto', productoRoutes)
router.use('/api-web/extra', extraRoutes)
router.use('/api-web/tipoPedido', tipoPedidoRoutes)
router.use('/api-web/cliente', clienteRoutes)
router.use('/api-web/direccion', direccionRoutes)
router.use('/api-web/pedido', pedidoRoutes)
router.use('/api-web/promocion', promocionRoutes)
router.use('/api-web/upload', uploadRoutes)

//rutas mobile
router.use('/api-mobile/rol', rolRoutes)
router.use('/api-mobile/colaborador', colaboradorRoutes)
router.use('/api-mobile/tipoPlatillo', tipoPlatilloRoutes)
router.use('/api-mobile/platillo', platilloRoutes)
router.use('/api-mobile/platilloDetalle', platilloDetalleRoutes)
router.use('/api-mobile/proveedor', proveedorRoutes)
router.use('/api-mobile/tipoMedida', tipoMedidaRoutes)
router.use('/api-mobile/categoria', categoriaRoutes)
router.use('/api-mobile/producto', productoRoutes)
router.use('/api-mobile/extra', extraRoutes)
router.use('/api-mobile/tipoPedido', tipoPedidoRoutes)
router.use('/api-mobile/cliente', clienteRoutes)
router.use('/api-mobile/direccion', direccionRoutes)
router.use('/api-mobile/pedido', pedidoRoutes)
router.use('/api-mobile/promocion', promocionRoutes)
router.use('/api-mobile/upload', uploadRoutes)

module.exports = router