const { Router } = require('express')

const router = Router();

const rolRoutes = require('./rol.routes')
const colaboradorRoutes = require('./colaborador.routes')
const tipoPlatilloRoutes = require('./tipoPlatillo.routes')
const platilloRoutes = require('./platillo.routes')
const platilloDetalleRoutes = require('./platilloDetalle.routes')
const proveedorRoutes = require('./proveedor.routes')
const tipoMedidaRoutes = require('./tipoMedida.routes')
const categoriaRoutes = require('./categoria.routes')
const productoRoutes = require('./producto.routes')
const extraRoutes = require('./extra.routes')
const tipoPedidoRoutes = require('./tipoPedido.routes')
const clienteRoutes = require('./cliente.routes')
const direccionRoutes = require('./direccion.routes')
const pedidoRoutes = require('./pedido.routes')

router.use('/api/rol', rolRoutes)
router.use('/api/colaborador', colaboradorRoutes)
router.use('/api/tipoPlatillo', tipoPlatilloRoutes)
router.use('/api/platillo', platilloRoutes)
router.use('/api/platilloDetalle', platilloDetalleRoutes)
router.use('/api/proveedor', proveedorRoutes)
router.use('/api/tipoMedida', tipoMedidaRoutes)
router.use('/api/categoria', categoriaRoutes)
router.use('/api/producto', productoRoutes)
router.use('/api/extra', extraRoutes)
router.use('/api/tipoPedido', tipoPedidoRoutes)
router.use('/api/cliente', clienteRoutes)
router.use('/api/direccion', direccionRoutes)
router.use('/api/pedido', pedidoRoutes)

module.exports = router